[tool.poetry]
name = "voicerecog"
version = "0.1.0"
description = ""
authors = ["sondeko <sondeko143@gmail.com>"]
license = "MIT"
readme = ["README.md", "LICENSE"]
repository = "https://github.com/sondeko143/vstreamer-tool"

[tool.poetry.dependencies]
google-cloud-translate = "^3.11.1"
python = ">=3.10,<3.12"
httpx = "^0.23.3"
pydantic = "^1.10.7"
aiofiles = "^23.1.0"
pyhumps = "^3.8.0"
voicevox-core = [
    { url = "https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.3/voicevox_core-0.14.3+cuda-cp38-abi3-win_amd64.whl", platform = "win32" },
    { url = "https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.3/voicevox_core-0.14.3+cpu-cp38-abi3-macosx_11_0_arm64.whl", platform = "darwin", markers = "platform_machine == 'arm64'" },
    { url = "https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.3/voicevox_core-0.14.3+cpu-cp38-abi3-macosx_10_7_x86_64.whl", platform = "darwin", markers = "platform_machine == 'x86_64'" },
    { url = "https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.3/voicevox_core-0.14.3+cpu-cp38-abi3-linux_x86_64.whl", platform = "linux", markers = "platform_machine == 'x86_64'" },
]
google-cloud-speech = "^2.19.0"
toml = "^0.10.2"
click = "^8.1.3"
vstreamer-protos = { url = "https://github.com/sondeko143/vstreamer-protos/releases/download/main-91cf58c5/vstreamer_protos-0.1.0-py3-none-any.whl" }

[tool.poetry.group.dev.dependencies]
docutils = "^0.19"
black = "^23.3.0"
isort = "^5.12.0"
bandit = "^1.7.5"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pytest-grpc = "^0.8.0"

[tool.poetry.group.torch]
optional = true

[tool.poetry.group.torch.dependencies]
openai-whisper = { git = "https://github.com/openai/whisper" }
torch = [
    { url = "https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-win_amd64.whl", platform = "win32" },
    { url = "https://download.pytorch.org/whl/cpu/torch-2.0.0-cp310-none-macosx_11_0_arm64.whl", platform = "darwin", markers = "platform_machine == 'arm64'" },
    { url = "https://download.pytorch.org/whl/cpu/torch-2.0.0-cp310-none-macosx_10_9_x86_64.whl", platform = "darwin", markers = "platform_machine == 'x86_64'" },
    { url = "https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-linux_x86_64.whl", platform = "linux" },
]
fairseq = "^0.12.2"
pyworld = "^0.3.3"
faiss-gpu = { version = "^1.7.2", platform = "linux" }
faiss-cpu = [
    { version = "^1.7.2", platform = "win32" },
    { version = "^1.7.2", platform = "darwin" },
]
onnxruntime-gpu = "^1.14.1"
torchaudio = [
    { url = "https://download.pytorch.org/whl/cu118/torchaudio-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl", platform = "win32" },
    { url = "https://download.pytorch.org/whl/cpu/torchaudio-2.0.1-cp310-cp310-macosx_11_0_arm64.whl", platform = "darwin", markers = "platform_machine == 'arm64'" },
    { url = "https://download.pytorch.org/whl/cpu/torchaudio-2.0.1-cp310-cp310-macosx_10_9_x86_64.whl", platform = "darwin", markers = "platform_machine == 'x86_64'" },
    { url = "https://download.pytorch.org/whl/cu118/torchaudio-2.0.1%2Bcu118-cp310-cp310-linux_x86_64.whl", platform = "linux" },
]
numpy = ">=1.18,<1.24"
scipy = "^1.10.1"

[tool.poetry.group.mozc]
optional = true

[tool.poetry.group.mozc.dependencies]
mozcpy = "^0.1.1"

[tool.poetry.group.vroid2]
optional = true

[tool.poetry.group.vroid2.dependencies]
pyvcroid2 = { git = "https://github.com/Nkyoku/pyvcroid2", platform = "win32" }

[tool.poetry.group.audio]
optional = true

[tool.poetry.group.audio.dependencies]
PyAudio = "^0.2.13"

[tool.poetry.group.gui]
optional = true

[tool.poetry.group.gui.dependencies]
ttkbootstrap = "^1.10.1"
pillow = "^9.5.0"

[tool.poetry.scripts]
vspeech = "vspeech.main:cmd"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = "."

[tool.pyright]
reportUnknownMemberType = "warning"
reportMissingTypeStubs = "warning"
reportUnknownVariableType = "warning"
